### PR TITLE
Fix Equipment Reservations Calendar in Admin Dashboard

### LINKED ISSUE #105: Disable non available hours
The reservation  calendar displayed in an equipment's "show" admin dashboard view should have all non-available (non-business) hours greyed out and blocked. At the moment, they appear as available (white background).

## Expected behavior
Showing non-available hours as greyed out (blocked).

## Current behavior
Every time slot has a white background

## Closing Criteria
- [x] Equipment's available hours (time slots) are shown in white
- [x] Hours (timeslots) outside equipment's available hours are shown in grey/blocked out

### PR DESCRIPTION
**Pull request by technical-boy**
### What does this PR do?

* Implements a feature that blocks (grays out) the calendar space that does not correspond to the specific equipment's registered available hours (not including reserved slots).
* Closes #105 

#### Merge Checklist:

- [x] The branch is up-to-date (i.e. rebased) with the base branch
- [x] Is GPA high enough?

### CODE REVIEW

File: app/dashboards/lab_space_dashboard.rb [hunk 1]
```diff
@@ -16,6 +16,7 @@ class LabSpaceDashboard < Administrate::BaseDashboard
     description: Field::Text,
     hours: Field::String,
     location: Field::String,
+    user: Field::BelongsTo,
```
Comment (AldoCervantes) [inline app/dashboards/lab_space_dashboard.rb]: This change is the same as this PR #159
